import type { Metadata } from "next";
import { Nunito } from "next/font/google";

import ClientOnly from "@/providers/ClientOnly";
import Header from "@/layout/Header";
import Modal from "@/modules/Modal/Modal";

import "./globals.css";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Renting House App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <ClientOnly>
          <Modal isOpen title="hello world" actionLabel="submit" />
          <Header />
        </ClientOnly>
        {children}
      </body>
    </html>
  );
}
